/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje.otomasyon;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ana_ekran extends javax.swing.JFrame {

    DefaultTableModel tablo = new DefaultTableModel();
    
    
    public ana_ekran() {
        initComponents();
        musteri_tablo.setModel(tablo);
        tablo.setColumnIdentifiers(new String[]{"Ad","Soyad","Telefon Numarası","Araç Plakası","Giriş Saati"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ad = new javax.swing.JLabel();
        soyad = new javax.swing.JLabel();
        telNo = new javax.swing.JLabel();
        plakaNo = new javax.swing.JLabel();
        girisSaat = new javax.swing.JLabel();
        sys_ad = new javax.swing.JTextField();
        sys_soyad = new javax.swing.JTextField();
        sys_tel_no = new javax.swing.JTextField();
        sys_arac_plaka = new javax.swing.JTextField();
        sys_giris_saat = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        sonlandir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        musteri_tablo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anasayfa");

        ad.setText("Ad :");

        soyad.setText("Soyad : ");

        telNo.setText("Telefon Numarası : ");

        plakaNo.setText("Araç Plakası : ");

        girisSaat.setText("Giriş Saati : ");

        sys_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sys_soyadActionPerformed(evt);
            }
        });

        kaydet.setText("Kaydet");
        kaydet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        sil.setText("Sil");
        sil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        cikis.setText("Çıkış Yap");
        cikis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        sonlandir.setText("Sistemi Sonlandır");
        sonlandir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sonlandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonlandirActionPerformed(evt);
            }
        });

        musteri_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(musteri_tablo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telNo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(girisSaat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plakaNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sys_ad)
                            .addComponent(sys_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(sys_tel_no)
                            .addComponent(sys_arac_plaka)
                            .addComponent(sys_giris_saat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kaydet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sonlandir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad)
                            .addComponent(sys_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyad)
                            .addComponent(sys_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telNo)
                            .addComponent(sys_tel_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plakaNo)
                            .addComponent(sys_arac_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(girisSaat)
                            .addComponent(sys_giris_saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(kaydet)
                        .addGap(18, 18, 18)
                        .addComponent(sil)
                        .addGap(18, 18, 18)
                        .addComponent(cikis)
                        .addGap(18, 18, 18)
                        .addComponent(sonlandir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sys_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sys_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sys_soyadActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        String ad = sys_ad.getText();
        String soyad = sys_soyad.getText();
        String telNo = sys_tel_no.getText();
        String plakaNo = sys_arac_plaka.getText();
        String saat = sys_giris_saat.getText();
        tablo.addRow(new String[]{ad,soyad,telNo,plakaNo,saat});
        sys_ad.setText("");
        sys_soyad.setText("");
        sys_tel_no.setText("");
        sys_arac_plaka.setText("");
        sys_giris_saat.setText("");
    }//GEN-LAST:event_kaydetActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        sys_ad.setText("");
        sys_soyad.setText("");
        sys_tel_no.setText("");
        sys_arac_plaka.setText("");
        sys_giris_saat.setText("");
    }//GEN-LAST:event_silActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        int hesap=0;
        String giris_saat = JOptionPane.showInputDialog("Giriş Saati : ");
        String cikis_saat = JOptionPane.showInputDialog("Çıkış Saati : ");
        Double grsSaat = Double.parseDouble(giris_saat);
        Double cksSaat = Double.parseDouble(cikis_saat);
        hesap = (int)(cksSaat-grsSaat)*5;
        JOptionPane.showMessageDialog(rootPane, " Ücretiniz : "+hesap);
        tablo.removeRow(musteri_tablo.getSelectedRow());
    }//GEN-LAST:event_cikisActionPerformed

    private void sonlandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonlandirActionPerformed
        dispose();
    }//GEN-LAST:event_sonlandirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana_ekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JButton cikis;
    private javax.swing.JLabel girisSaat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydet;
    private javax.swing.JTable musteri_tablo;
    private javax.swing.JLabel plakaNo;
    private javax.swing.JButton sil;
    private javax.swing.JButton sonlandir;
    private javax.swing.JLabel soyad;
    private javax.swing.JTextField sys_ad;
    private javax.swing.JTextField sys_arac_plaka;
    private javax.swing.JTextField sys_giris_saat;
    private javax.swing.JTextField sys_soyad;
    private javax.swing.JTextField sys_tel_no;
    private javax.swing.JLabel telNo;
    // End of variables declaration//GEN-END:variables
}
